Blood = []
Blood.append(['O', 'O', 'O'])
Blood.append(['O', 'A', 'A'])
Blood.append(['O', 'A', 'O'])
Blood.append(['O', 'B', 'B'])
Blood.append(['O', 'B', 'O'])
Blood.append(['O', 'AB', 'A'])
Blood.append(['O', 'AB', 'B'])
Blood.append(['A', 'A', 'A'])
Blood.append(['A', 'A', 'O'])
Blood.append(['A', 'B', 'A'])
Blood.append(['A', 'B', 'B'])
Blood.append(['A', 'B', 'O'])
Blood.append(['A', 'B', 'AB'])
Blood.append(['A', 'AB', 'A'])
Blood.append(['A', 'AB', 'B'])
Blood.append(['A', 'AB', 'AB'])
Blood.append(['B', 'B', 'B'])
Blood.append(['B', 'B', 'O'])
Blood.append(['B', 'AB', 'A'])
Blood.append(['B', 'AB', 'B'])
Blood.append(['B', 'AB', 'AB'])
Blood.append(['AB', 'AB', 'A'])
Blood.append(['AB', 'AB', 'B'])
Blood.append(['AB', 'AB', 'AB'])
n = int(input("測試的資料量:"))
for i in range(n):
    ckBlood = input("依序輸入父、母、子女的血型:").split()
    if ckBlood in Blood:
        print("YES")
    else:
        print('IMPOSSIBLE')